# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "Services"
  identifier = "Services"
  url = "#services"
  weight = 12
  
[[main]]
  name = "Our Services"
  parent = "Services"
  url = "#services"
  weight = 3
  
[[main]]
  name = "Psychotherapy"
  parent = "Services"
  url = "#individual_psychotherapy"
  weight = 5
 
[[main]]
  name = "Forms"
  parent = "Services"
  url = "/forms"
  weight = 13

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  name = "People"
  url = "people"
  weight = 30

# [[main]]
#  name = "Events"
#  url = "event"
#  weight = 40

[[main]]
  name = "About"
  identifier = "About"
  url = "#"
  weight = 50
  
[[main]]
  name = "About Psychotherapy"
  parent = "About"
  url = "/about/psychotherapy"
  weight = 5

[[main]]
  name = "FAQ"
  parent = "About"
  url = "/faq"
  weight = 10

[[main]]
  name = "Fees"
  parent = "About"
  url = "/about/fees"
  weight = 90

# [[main]]
#   name = "Covid-19"
#   parent = "About"
#   url = "/about/covid"
#   weight = 97
  
[[main]]
  name = "In a crisis?"
  parent = "About"
  url = "/about/crisis"
  weight = 99

[[main]]
  name = "Book now"
  url = "/booking"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70
