[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.97.3"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  #[plugins.inputs.thresholds]
  #  performance = 0.4
  #  accessibility = 0.4
  #  best-practices = 0.4
  #  seo = 0.4
  #  pwa = 0.4

  [[plugins.inputs.audits]]
    #url = "https://www.therapynottingham.co.uk"
    #url = "https://therapynottingham.netlify.app"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[redirects]]
  from = "/contact"
  to = "https://us10.list-manage.com/contact-form?u=d64b1f151f0dee2ea7b9863e5&form_id=a64c7dbd3f2f297a325771e9a49a27ec"
  status = 301
  force = true # COMMENT: ensure that we always redirect